script:
  - git branch
  - ls
  - mkdir asd
  - ls
  - git checkout master
  - ls
  - git checkout a
  - ls
  - mkdir djlksajdlksa
  - ls
  - diff -u <(git rev-list --first-parent a)              <(git rev-list --first-parent master) |      sed -ne 's/^ //p' | head -1 | xargs git reset --hard
  - ls
